### ISSUE TITLE
Avoid duplication of macro docstings

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana-followup#19]
Documentation of the macros in the macro catalogue is duplicated. We need to find a way on how to reuse the macro classes/functions docstrings.

**Comment by cmft** [comment]
We can avoid duplication using references. See [this](https://stackoverflow.com/questions/22700606/how-would-i-cross-reference-a-function-generated-by-autodoc-in-sphinx)

**Comment by reszelaz** [comment]
Kamino closed and cloned this issue to sardana-org/sardana
