### ISSUE TITLE
Evaluate video conference tools

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana-followup#25]
Ones that we consider right now are:
* Jitsi (https://meet.jit.si/)
* OpenMeetings (https://openmeetings.apache.org/index.html)
* Google Hangouts (https://hangouts.google.com/)

but the list may (and probably should) be expanded.

**Comment by reszelaz** [comment]
Today with @amilan we tested Jitsi. It worked quite well. We tested screen sharing. The only thing is that @amilan was forced to use it with Google Chrome (it requires an extension to be installed in the browser). With Firefox it did not work.
Apart form that, it looked like Jitsi has planty of features: recording, live streaming, YouTube integration, etc.
We need to try it with more users connected at the same time.

**Comment by reszelaz** [comment]
Today we made the follow-up meeting using Jitsi. It worked well with 4 participants!

Before officially switching to this tool we would like to test it with at least 8 participants. For that reason we are going to make a test call tomorrow. If you have time, please join us - the more we are the better. 

For that, open in a web browser: https://meet.jit.si and in the "Start a new meeting pop-up" type: "sardana" and click on "Go". We meet tomorrow: 14.12.2019 on 14:00 CET.

See you there!

**Comment by guifrecuni** [comment]
From my side it was really smooth, I'd vote to continue with this tool.

**Comment by daneos** [comment]
I had some troubles with sound, but I think it was caused by many people from SOLARIS using the same internet connection to connect to Jitsi.
I also vote to continue with Jitsi.

**Comment by reszelaz** [comment]
I think we are happy with Jitsi. So I close this issue.
