### ISSUE TITLE
Evaluate tools for remote pair programming

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana-followup#26]

**Comment by reszelaz** [comment]
This issue has advanced after som pair-programming sessions I had with @cpascual, @13bscsaamjad and @HEnquist. I paste here a nice summary of the available options by @cpascual:

> This email is to mention various proposed solutions for remote pair programming. Of course, I make a requirement that it works with Free Software (in general I think it is important, but specially for "collaborative" solutions, in order not to force other people to install non-free software).
> 
> - PyCharm now offers a plugin in beta (Code With Me)  [1]. For now it is free to use but it won't probably be in the future. I couldn't make it work. Zibi reported that he managed to work with it but it was not very smooth. I see that there is another (3rd party) plugin (GitDuck) [2] which we could also try...
> 
> - VSCode also has a plugin (LiveShare ) [3]. Zibi has tried it satisfactorily with VSCode, but we couldn't make it work with the free version of the IDE (VSCodium) [4]. Also, this service requires using microsoft servers...
> 
> - ssh + tmux [5] + emacs/vi/nano (thanks Tiago for the suggestion). It looks good,  but it has the problem of requiring to work on a machine with an open ssh port (not ideal, specially if working behind a firewall). But this can be solved replacing "ssh+tmux" by tmate [6] or upterm[7] which use a reverse ssh tunnel to bypass firewalls. On the paper, this looks like the simplest and more transparent method (but I need to test it to get a real world feeling)
> 
> This is the situation for now. Do any of you know of other solutions?
> 
> 
> Carlos
> 
> 
> [1] https://blog.jetbrains.com/blog/2020/10/23/code-with-me-jetbrains-ides-v2020-3/
> 
> [2] https://plugins.jetbrains.com/plugin/14919-gitduck-pair-programming-tool
> 
> [3] https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare
> 
> [4] https://github.com/VSCodium/vscodium/issues/320
> 
> [5] https://github.com/tmux/tmux/wiki/Getting-Started
> 
> [6] https://tmate.io/
> 
> [7] https://github.com/owenthereal/upterm
> 

I confim that the the experience with VSCode that we had with @13bscsaamjad and @HEnquist was better than with Code With Me from PyCharm.

**Comment by cpascual** [comment]
Hi, I encourage to try with [tmate](https://tmate.io/). I only did preliminary tests, but it LGTM:
- only the "host" needs to install tmate (the client can either use an ssh client or even use just a web browser)
- the host can provide the client with a "read-only" key or with a fully interactive key
- it is fully open source (unlike the VSC or PyCharm plugins)

**Comment by reszelaz** [comment]
Different options were evaluated and are listed above. We already use them in our development. I think there is no necessity to keep this one opened.

**Comment by reszelaz** [comment]
Recently I worked both with VS Code (Live Share) and PyCharm (Code With Me) and both work well now.
