### ISSUE TITLE
Provide newsletter for users

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana-followup#32]
* We agreed that it is a good idea to work on newsletter together
* Newsletter should be created continuous as CHANGELOG as unreleased and then, on the release, it should be frozen and released.
* Newsletter will be announced on the release email.
* To be decided the format for it: could be markdown, sphinx and part of the documentation, etc.
* It should be written in user friendly language and supported by examples. But in general it should point to the documentation.

**Comment by cpascual** [comment]
Hi, I wasn't on the discussion and I do not want to reopen it, but I just give my opinion about this: 

Opening a newsletter is opening a new channel of documentation. This introduces a great risk of dispersing the sources of docs (increasing user confusion). Note that a user looking for documentation may already find it in or be directed to: 
- the official docs
- a github issue/pr
- a SEP
- inline code comments
- the wiki
- a thread in the mailing list

IMHO adding yet another channel is only worth considering when the community has more capacity of producing documentation than what can be absorbed through the existing channels or when the source of the documentation cannot be easily integrated in one of the existing channels (e.g. the wiki is interesting for contributed docs not produced/coordinated directly by the development team)

I understand that the idea of the newsletter is just to complement the release messages, pointing to docs and providing practical examples, but IMHO, given that the potential authors of the newsletter already have full access to modifying the official docs (and that the official docs are far from being complete), I think that it is better to concentrate the scarce documentation capacity on the official docs / SEPs and just point to them in the release message.

... but as I said, I do not want to reopen the discussion if an agreement was already reached in the follow-up  ;)

**Comment by reszelaz** [comment]
Thanks for the comment. There were no conclussions yet reached and we will continue on the next followup.
The idea is to have something like the changelog but oriented to the users. We also thought to use links to the documentation from the newsletter. The format was not yet discussed but IMHO it should form part of the official docs. Something like: "What's new in Sardana 2.6" with links to other chapters of the docs..

Another thing would be to make the changelog more user-friendly..

**Comment by teresanunez** [comment]
I actually agree with both of you ... I also think that it is not good to have another source of documentation, but the newsletter should be somehow a way of making the users aware of new
features. We could also make the other way around and put in the newsletter a link to the documentation where the new feature is described.

**Comment by guifrecuni** [comment]
I'd propose to start with a RELEASE.md file next to CHANGELOG.md focused on explaining to end-users the new features and possible impacts. Nevertheless, I am not sure if we should list all or some bugfixes in this document... maybe those opened by users?

**Comment by reszelaz** [comment]
Thanks for your comments. RELEASE.md is another option. We will evaluate it when we come back to this brainstorming on the next follow-up meeting.

>  I am not sure if we should list all or some bugfixes in this document... maybe those opened by users?

I would say that not the whole content of the CHANGELOG should be placed in the "newsletter" but only the features/bug fixes that are meaningful to the end users. And I think we will need to asses each case separatelly and the requestor field can not be used for that.

**Comment by reszelaz** [comment]
As we agreed on the last follow-up meeting, until we decide of the format of the newsletter, for the moment we draft it in the wiki page.
Since I've merged one new feature, I've added it the newsletter draft. You can find it [here](https://github.com/sardana-org/sardana/wiki/Newsletter#pre-scan-snapshot-can-now-be-configure-also-from-the-spock-cli-using-macros).

**Comment by reszelaz** [comment]
With this section: https://sardana-controls.org/news.html I think we could proceed to close this issue. Many thanks for your contributions.
